name: UI tests
on: [pull_request]

jobs:
  Test:
    runs-on: macos-13
    name: ClickAcceptAllButtonTest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v3
    - name: AVD cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-34
    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        target: google_apis
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        arch: x86_64
        script: echo "Generated AVD snapshot for caching."
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
    - name: Start emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        target: google_apis
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        arch: x86_64
        script: |
          echo "Emulator working"
          # : - name: Install and run Appium Server
          # :   run: |
          npm i --location=global appium
          appium driver install uiautomator2
          appium driver install xcuitest
          appium plugin install --source=npm appium-altunity-plugin
          pwd && cd ~/work/unity-sdk/unity-sdk && pwd && mkdir logs && cd logs && echo "appium" > appiumLog.txt && pwd && ls
          appium --use-plugins=altunity &>~/work/unity-sdk/unity-sdk/logs/appiumLog.txt &
          # : - name: Install and run AltTester Server
          # :   run: |
          cd ~/work/unity-sdk/unity-sdk/logs && echo "alttester" > altTesterLog.txt && echo "alttester" > altTesterComLog.txt && pwd && ls
          cd ~/work/unity-sdk/unity-sdk && wget https://alttester.com/app/uploads/AltTester/desktop/AltTesterDesktopPackageMac__v2.1.2.zip && unzip AltTesterDesktopPackageMac__v2.1.2.zip && cd AltTesterDesktopPackageMac__v2.1.2 && hdiutil attach AltTesterDesktop__v2.1.2.dmg && cp -R /Volumes/AltTesterDesktop/AltTesterDesktop.app ~/work/unity-sdk/unity-sdk
          cd ~/work/unity-sdk/unity-sdk && AltTesterDesktop.app/Contents/MacOS/AltTesterDesktop -batchmode -nographics -port 13000 -license ${{ secrets.ALTTESTERLICENSEKEY }} -termsAndConditionsAccepted -logfile ~/work/unity-sdk/unity-sdk/logs/altTesterLog.txt &>~/work/unity-sdk/unity-sdk/logs/altTesterComLog.txt &
          # : - name: Install and run Appium Server
          # :  run: |
          cd ~/work/unity-sdk/unity-sdk && chmod -R 777 UI-TESTS
          cd ~/work/unity-sdk/unity-sdk/UI-TESTS && dotnet test -s android.runsettings --filter Name=ClickAcceptAllButtonTest || true
          echo "done"
    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs/
        compression-level: 0
        